# Site settings
title: Experience variety
email: denisaa.stan@gmail.com
author: Denisa Stan
description: "A blog about ..."
baseurl: ""
url: "denisa.stan.github.io"
twitter_username: denisaastan
github_username:  denisastan
linkedin_username: denisa-stan

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

gems:
  - jekyll-sitemap
  - jekyll-paginate